WITH BIKE_DATE AS(

    SELECT
    STARTED_AT,
    TO_TIMESTAMP(STARTED_AT) AS TIMESTAMP,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    CASE
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun')
    THEN 'WEEKEND'
    ELSE 'BusinessDay'
    END AS DAY_TYPE,
    CASE
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN ('3','4','5')
    THEN 'Spring'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN ('6','7','8')
    THEN 'Summar'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN ('9','10','11')
    THEN 'Autumn'
    ELSE 'Winter' END AS SEASONS
    FROM
  {{ source('demo', 'bike') }}
  WHERE STARTED_AT != 'started_at'
)

SELECT * FROM BIKE_DATE