WITH BIKE_DATE AS(

    SELECT
    STARTED_AT,
    TO_TIMESTAMP(STARTED_AT) AS TIMESTAMP,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    {{DAYNAME('STARTED_AT')}},
    {{SEASONS('STARTED_AT')}},
    {{fn1('STARTED_AT')}}

    FROM
  {{ source('demo', 'bike') }}
  WHERE STARTED_AT != 'started_at'
)

SELECT * FROM BIKE_DATE